[package]
name = "nexus-steam-integration"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
name = "nexus_steam_integration"

[dependencies]
arcdps-imgui = "0.8.0"
steamworks = { version = "0.11.0", features = ["raw-bindings"] }

[dependencies.nexus-rs]
git = "https://github.com/belst/raidcore_bindings-rs"
rev = "423e14136e2adec56ba392e2db4e0e61f8507de5"

[dependencies.windows]
version = "0.53.0"
features = ["Win32_System_LibraryLoader", "Win32_Foundation", "Win32_System_SystemServices"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"